### ISSUE TITLE
Problème sous linux

### ISSUE THREAD

**Issue by chalbin73** [IGNF/IGNMap#1]
Bonjour,

Le logiciel ne fonctionne pas sur linux: dès l'execution on a :
Maximum number of clients reached
Maximum number of clients reached

et une segmentation fault.
Savez vous comment le lancer ?

**Comment by fbecir** [comment]
Bonsoir
Sous quelle version de LINUX êtes-vous ?
La version LINUX a été testée sous Ubuntu 18 et Ubuntu 22 et fonctionne.
Les développements sont toutefois faits principalement sous LINUX. Avez-vous essayé de recompiler sur votre machine ?

Cordialement

**Comment by fbecir** [comment]
Il semblerait que cette erreur "Maximum number of clients reached" soit une erreur soit liée à X-Window :
https://askubuntu.com/questions/1282094/ubuntu-18-04-maximum-number-of-clients-reached-related-to-dbus-daemon
