### ISSUE TITLE
Chargement couche PCRS

### ISSUE THREAD

**Issue by eolmapper** [IGNF/IGNMap#5]
Je n'arrive pas à charger la couche PCRS en flux WMTS.
J'utilise les paramètres suivant:
Serveur: data.geopf.fr/wmts
couche: PCRS.LAMB93
TMS: 2154_5cm_6_22

J'ai essayer également sans succès avec 
serveur:data.geopf.fr/wmts?SERVICE=WMTS&VERSION=1.0.0&REQUEST=GetCapabilities

Je charge sans problème d'autres couches comme ORTHOIMAGERY.ORTHOPHOTOS.ORTHO-EXPRESS.2024

Est-ce un problème logiciel, ou bien de mauvais paramétrage?

**Comment by fbecir** [comment]
Pour l'instant, la lecture du WMTS est faite sans tenir compte du GetCapabilities.
En particulier, on considère que toutes les couches sont en WebMercator. Dans le cas du PCRS, on est en Lambert 93 ... d'où le problème.

**Comment by eolmapper** [comment]
Merci pour la réponse, je me doutait un peut que ça pouvait venir de là.

**Comment by fbecir** [comment]
Pour compléter, quasiment toutes les couches de la Géoplateforme sont en WebMercator et en général, les sites exposent les données en WebMercator, d'où le raccourci. Mais, l'objectif est bien de prendre en compte la bonne projection.
Pour l'instant, IGNMap ne s'appuie que sur un jeu limité de projections (les projections légales Françaises) donc on est limité pour les travaux hors France. A terme, il faudra intégrer une bibliothèque comme PROJ.

**Comment by fbecir** [comment]
La nouvelle version d'IGNMap (la 0.1.0) inclut un nouvel outil pour l'import de serveurs WMTS (et aussi TMS).
La gestion du WMTS est maintenant correcte avec une bonne prise en compte de la projection indiquée (à condition bien-sûr que cette projection soit connue par IGNMap, donc pour l'instant une projection légale Française ou du WebMercator).
Donc maintenant il est possible de charger la couche PCRS.LAMB93.
